### ISSUE TITLE
Subtitle XML format has changed, and broke subtitle functionality

### ISSUE THREAD

**Issue by sj6406** [vonH/plugin.video.iplayerwww#326]
The subtitles are not working on 3.0.48 on LibreELEC 9.2.3 (kernel: Linux 4.19.122). The same programmes on https://www.bbc.co.uk/iplayer using Firefox have subtitles.

I've tried turning them on and off. I've also changed the permissions of `/storage/.kodi/userdata/addon_data/plugin.video.iplayerwww` to `drwxrwxrwx`. I've also created `iplayer.srt` in that folder (using `touch`) and gave it permissions `-rw-rw-rw-`.

Any help would be appreciated.

**Comment by sj6406** [comment]
They also don't work on `Kodi 18.7` on `Raspbian 10 (Buster)`.

**Comment by sj6406** [comment]
Also doesn't work on Kodi 18.7 on Windows 10 64-bit.

**Comment by CaptainTK** [comment]
Does this affect a particular programme only, or did subtitles stop working for you completely? If it is only specific programmes, please give an example so I can duplicate the issue.

**Comment by sj6406** [comment]
I tried several programmes. Like this one: [https://www.bbc.co.uk/iplayer/episode/m000k4bs/dragons-den-best-ever-pitches-4-entrepreneurs-fight-back].

I've tried it on Kodi 18.7 on a Pi 4 Model B (both natively and on Raspberry Pi OS), and on Kodi 18.7 and 18.2 on Windows 10 Home build 1903. I'm profoundly deaf, so no subtitles is a deal breaker for me. I'm trying to set the Pi up as a media player.

**Comment by CaptainTK** [comment]
Thanks for reporting this issue @sj6406. The XML format of the subtitles has changed, which broke the subtitle functionality completely. I am looking into it, but can't say right now if this is an easy or a complex fix.

**Comment by sj6406** [comment]
If there is anything I can do to help just let me know. I'm a retired software engineer.

**Comment by CaptainTK** [comment]
I implemented a first fix, which probably still contains bugs. It definitly contains missing fallbacks for several cases. You can find the update here: https://github.com/vonH/plugin.video.iplayerwww/releases/tag/3.0.49alpha.

Please download the ZIP, install on your system, and give it a try for a couple of days. Let me know anything that is off, programmes where subtitles are missing, or partially missing, or any other oddity.

Once this has been sorted out, I will release this as a general update.

**Comment by sj6406** [comment]
@CaptainTK Thanks, I'll do that. Much appreciated.

**Comment by sj6406** [comment]
@CaptainTK I'm afraid it is still not working. I uninstalled the latest release and installed 3.0.49alpha from zip. The Dragon's Den example I gave you in https://github.com/vonH/plugin.video.iplayerwww/issues/326#issuecomment-646261842 is still not showing the subtitles.

I tried restarting Kodi and I also tried toggling the enable subtitles switch. I also ran it for a bit to see if they would come up. But no luck. :(

**Comment by CaptainTK** [comment]
Now that's odd. I used that very episode, and it worked well in my end.

Can you check your Kodi userdata folder please? There should be a subfolder

addon_data/plugin.video.iplayerwww

Inside this directory, there should be the iPlayer.srt file which contains the subtitles of the last programme you played. Just open it with some text editor, and see if you can find any content. If the file is present, and filled, something else is off.

**Comment by sj6406** [comment]
There is no iplayer.srt. Here is how the folders and permissions look:
```
urKodi:~/.kodi/userdata/addon_data # ls -al
total 6
drwxr-xr-x    6 root     root          1024 Jun 19 15:27 .
drwxr-xr-x   11 root     root          1024 Jun 18 14:52 ..
drwxr-xr-x    3 root     root          1024 Apr 11  2019 peripheral.joystick
drwxr-xr-x    2 root     root          1024 Jun 19 15:28 plugin.video.iplayerwww
drwxr-xr-x    2 root     root          1024 Apr 11  2019 service.libreelec.settings
drwxr-xr-x    2 root     root          1024 Apr 11  2019 skin.estuary
OurKodi:~/.kodi/userdata/addon_data # cd plugin.video.iplayerwww/
OurKodi:~/.kodi/userdata/addon_data/plugin.video.iplayerwww # ls -al
total 6
drwxr-xr-x    2 root     root          1024 Jun 19 15:28 .
drwxr-xr-x    6 root     root          1024 Jun 19 15:27 ..
-rw-r--r--    1 root     root           405 Jun 19 15:43 iplayer.cookies
-rw-r--r--    1 root     root          2390 Jun 19 15:28 settings.xml
OurKodi:~/.kodi/userdata/addon_data/plugin.video.iplayerwww #
```
I did think it might be a directory permissions issue, but if `iplayer.cookies` can be written then surely `iplayer.srt` can too?

**Comment by sj6406** [comment]
I've tried adding iplayer.srt, but still no joy:
```
OurKodi:~/.kodi/userdata/addon_data/plugin.video.iplayerwww # ll
total 6
drwxrwxrwx    2 root     root          1024 Jun 20 13:48 ./
drwxr-xr-x    6 root     root          1024 Jun 19 15:27 ../
-rw-r--r--    1 root     root           405 Jun 20 13:45 iplayer.cookies
-rw-r--r--    1 root     root             0 Jun 20 13:48 iplayer.srt
-rw-r--r--    1 root     root          2390 Jun 19 15:28 settings.xml
OurKodi:~/.kodi/userdata/addon_data/plugin.video.iplayerwww # chmod ugo+w iplayer.srt
OurKodi:~/.kodi/userdata/addon_data/plugin.video.iplayerwww # ll
total 6
drwxrwxrwx    2 root     root          1024 Jun 20 13:48 ./
drwxr-xr-x    6 root     root          1024 Jun 19 15:27 ../
-rw-r--r--    1 root     root           405 Jun 20 13:45 iplayer.cookies
-rw-rw-rw-    1 root     root             0 Jun 20 13:48 iplayer.srt
-rw-r--r--    1 root     root          2390 Jun 19 15:28 settings.xml
```
I'll try Kodi on Windows.

**Comment by CaptainTK** [comment]
That's really weired. Yes, permissions look fine, so the file should be created. I just tried again, and it worked like a charm for the programme you mentioned before. However, I came across other programmes, which use a different format for subtitles. This is pretty annoying. So the fixes should work for some programmes, but it may break others.

**Comment by CaptainTK** [comment]
I just added compatibility for some more subtitles in [3.0.49~alpha2](https://github.com/vonH/plugin.video.iplayerwww/releases/tag/3.0.49alpha2). Please use this for further testing. I confirmed once again that it works on the programme you mentioned above.

**Comment by sj6406** [comment]
I'll try that. I've tried it on Kodi on Windows and still can't get the subtitles. I also tried running Kodi with administrator privileges and still could not get the subtitles. I'll try alpha2.

I don't know if it is relevant, but if I go to the iPlayer WWW settings on the _General_ pane, under _Video settings_ I can change _Play Signed programmes when available_ and _Play Audio Described programmes when available_. But I cannot highlight or change _Use subtitles when available_. It feels to me like something relating to the subtitles is missing; maybe I haven't got some essential component installed?

**Comment by CaptainTK** [comment]
Now we're getting somewhere.

If the _Use subtitles when available_ switch is not enabled, the add-on will not show any subtitles. Since the add-on needs to bypass Kodi's usual subtitle mechanism, it does not care about the global settings. I do not know why you might be unable to highlight or change the setting. The only situation, in which I ever had difficulties changing the value was, when it was just not fully in focus. Try scrolling down or using cursor keys in the settings pane, to see if you can then change the value.

Once this is activated, subtitles should start to show up, but may still not work 100% correctly in some cases.

**Comment by sj6406** [comment]
The subtitles are on now. \O/ I used the arrow keys to highlight _Use Subtitles..._ then the mouse to switch it on and I can now get subtitles on Dragon's Den. That's with 3.0.49alpha on Kodi 18.7 on Libreelec on the Pi 4.

I'll upgrade it to alpha2 and keep it running in the background to see how it goes.

**Comment by CaptainTK** [comment]
Fixed in latest release.
