### ISSUE TITLE
Subtitle colours

### ISSUE THREAD

**Issue by sunjaxx** [vonH/plugin.video.iplayerwww#353]
Hi, thanks for this. I believe subtitles have a couple of (unrelated?) issues:

1) Subtitles colours are not the same in the BBC app and Kodi add-on.

2) When different persons are talking, subtitles that end up in the same screen have usually different colours, but they end up having the same colour in the Kodi add-on.

See screenshots below showing both issues: the original blue and white subtitles (both) become
 red.
Thanks!

![bbc](https://user-images.githubusercontent.com/30780852/214923122-cd58f8eb-f9c0-4df3-8339-95f0edd35660.png)
![kodi](https://user-images.githubusercontent.com/30780852/214924287-b328f801-a536-4990-980b-2e9a326f4349.png)

**Comment by CaptainTK** [comment]
Thanks for reporting this. Looks like an issue with subtitle conversion. For your information: The subtitle format used by the Beeb is not supported by Kodi, so the subtitles need to be downloaded and converted before starting playback.

Would you mind letting me know which programme/episode this is? This will help me look into the issue faster.

**Comment by sunjaxx** [comment]
Sure, the screenshots are from happy valley, season 2, episode 2 (intro/recap section).

**Comment by CaptainTK** [comment]
Thanks, this made it easy for me to understand the issue, @sunjaxx .

Are you well versed in Kodi?

If so, would you mind trying the fix that I just committed?
If not, just let me know, and I will prepare a downloadable Beta for you.

**Comment by sunjaxx** [comment]
Let me try later today, I will let you know...

**Comment by sunjaxx** [comment]
So, issue #2 seems fixed, but not #1: colours are still different than the original ones (in particular, a lot of subtitles end up being red, which is not ideal / is rarely the case on the original subtitles):

![Screenshot_20230129-074313](https://user-images.githubusercontent.com/30780852/215312736-09d69310-423e-4357-87ca-74935936dce3.png)

Thanks!

**Comment by CaptainTK** [comment]
I cannot duplicate that issue on my end. Subtitles show up in the same colors as on the website. In particular, I get no red subtitles at all.

Is it possible that there are some settings on your system causing this issue?

**Comment by sunjaxx** [comment]
I checked and no, the KODI subtitles settings I have are all the default ones (i.e. white colour, which I guess is anyway ignored when subtitles have specific colours) apart from the font used. (I even tried to change that back to the default font - even thought it couldn't really be the reason - and still get red subtitles.)

I also checked on my (android) tablet, and I get red ones as well... Can it be somehow related to... android? (What OS did you test it on?)

Thanks!

**Comment by sunjaxx** [comment]
PS: Can I somehow access the ttml raw subtitle that is downloaded by the plugin before the conversion, to check the raw colours codes?

**Comment by CaptainTK** [comment]
That’s really odd. I tested on Linux and it works fine.

The original xml is not stored. It is converted on the fly, but the resulting ttml is indeed stored in the %USERDATA%/addon_data/plugin.video.iplayerwww folder. The file is called iplayer.srt. On Android the full path should be 

`Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.iplayerwww`

It would be really strange if the conversion works on Linux, but not on Android as that is essentially a Linux, too.

**Comment by sunjaxx** [comment]
Uhm, that's indeed strange. If I look at "iplayer.srt", I get (for that particular subtitles from the screenshots above):

```
10
00:00:22,520 --> 00:00:25,080
What do you want? <font color="yellow">Â£1,000 a month.<br /></font>I can't, Vicky!
```

Shouldn't there also be two more '<font color=...', one for "_What do you want?_" and one for "_I can't, Vicky!_"? (Although this  wouldn't explain why I get - on two different KODIs - red text for "_£1,000 a month_", I guess...)

**Comment by CaptainTK** [comment]
You are right. This line _should_ have additional formatting. Check this out: 742c48641c5e86616a54133117bba086f622d610. This should fix it for that line.

Be aware that there are some lines which do not provide any formatting in the Beeb's source file. In my instance, Kodi falls back to the last set colour. I am not sure what the "correct" behaviour would be in that situation. Perhaps fall back to the "default" style? Strangely enough that is never used as direct formatting in the original XML. However, it was used in the past.

Examples from the test episode are:

1. Time index 00:00:07,6: Clare?
2. Time index 00:00:00:16,96: Now, they're accusing me of strangling
3. Time index 00:00:00:18,64: an bottling Lynn Dewhurst

Let me know how they show up on your end, please.

**Comment by sunjaxx** [comment]
Not quite there yet.... The "iplayer.srt" output is now:

```
10
00:00:22,520 --> 00:00:25,080
<font color="cyan">What do you want? <font color="yellow">Â£1,000 a month.<br /></font>I can't, Vicky!</font>
```
(so, nested <fonts> and still missing the 3rd one...?) and I anyway get:

What do you want? **RED**
Â£1,000 a month. **RED**
I can't, Vicky! **WHITE**

**Comment by CaptainTK** [comment]
The file is as expected. Why should the nested format not work? It does for me. I can’t get my head around the colours you see. This is most strange.

Perhaps that is a difference between Linux and Android.

**Comment by sunjaxx** [comment]
I have the impression (android?) doesn't like colours specified as **names**. If I edit iplayer.srt and replace (for example) "yellow" with "#ffff00", then the colour is shown as yellow.

On nesting, I didn't know it was a valid option. And I don't know if it's related, but if I change 

```
10
00:00:22,520 --> 00:00:25,080
<font color="cyan">What do you want? <font color="yellow">Â£1,000 a month.<br /></font>I can't, Vicky!</font>
```

into:

```
10
00:00:22,520 --> 00:00:25,080
<font color="#00ffff">What do you want? <font color="#ffff00">Â£1,000 a month.<br /></font>I can't, Vicky!</font>
```

I get:

What do you want? **cyan** (good!)
Â£1,000 a month. **yellow** (good!)
I can't, Vicky! **white** (not good)

**Comment by CaptainTK** [comment]
It makes no sense to me why Android should not be capable of working with names instead of hex for colours. So my bet is still on issues with (poorly) nested statements.

I believe I figured out a way to avoid nested statements with this commit: 9f5a5d2924b2e208889d8ca79448ee17dd29d422.

The first shot of the new code did have adverse effects for older programmes, which have a different subtitle format. I don't know how many different versions there are, so before this will be released, it needs some serious testing on various programmes covering production dates over the last 10 years at least.

However, the big question remains: Will Android be able to cope with names now that everything is beautifully arranged?

**Comment by sunjaxx** [comment]
Thanks! I think you are missing a " somwhere here:

`text=text+'<font color="'+default_color[0]+'>'+content+'</font>'`

...because at the moment I get things like:

```
18
00:01:13,840 --> 00:01:15,280
<font color="cyan>No, of course I didn't!</font>
```

But even fixing that, they remain all red... I really think the color names are not being recognized, and that's why they all become red!

**Comment by sunjaxx** [comment]
PS: happy to help with testing on older programmes, if needed at some point!

**Comment by CaptainTK** [comment]
You are right, there was a quote missing. Strangely enough, it worked fine for me here. Kodi on Linux appears to be extremely tolerant regarding formatting errors.

You can find the extra quote here: 59e1e903f9c068e82488a0fe46e41a56b5221119.

**Comment by CaptainTK** [comment]
You are right, there are actually two quotes missing. Strangely enough it still worked perfectly for me. Kodi on Linux must be extremely tolerant regarding formatting errors.

Both quotes added here: b801a7adf7467215e4222969bd73a5eaa4c90ad9

**Comment by CaptainTK** [comment]
"But even fixing that, they remain all red... I really think the color names are not being recognized, and that's why they all become red!"

That would be a shame to say the least. In my opinion, it would be a bug in the Android port as other platforms can cope with colour names (and much worse).

**Comment by sunjaxx** [comment]
I can confirm they are still red.... 
Would it be an option to convert names to hex codes as part of the srt conversion? Or you say it's maybe a bug of kodi/android (?), so it should rather be fixed elsewhere?

**Comment by CaptainTK** [comment]
I thought about converting already. The challenge is this: I cannot find a standard substitution table within Kodi‘s Python interpreter, and I want to avoid creating it manually. After all, you never know which colours will be used in the future. Standard Python 3 does have suitable modules, but they are not available in Kodi.

**Comment by sunjaxx** [comment]
According to the [BBC subtitle guidelines](https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Colours), only 4 colours can be used, so I would not see a manual mapping - without calling other python modules - a big issue. I would be happy to test that option on a variety of BBC programs.

<html>
<body>
<div class="header-wrapper-h4" style="box-sizing: inherit; margin-top: 2.32031rem; margin-bottom: 1.54688rem; color: rgb(0, 0, 0); font-family: ReithSans, Arial, Helvetica, freesans, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 246, 246); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h4 id="Speaker-colours" class="toc-header display-header-elements-inline" style="max-width: 35rem; display: inline-block; box-sizing: inherit; font-family: ReithSerif, serif; font-size: 1.5rem; line-height: 1.75rem; margin: 0px;">Speaker colours</h4><a class="header-link" href="https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Speaker-colours" style="background-color: transparent; display: inline-block; position: relative; left: 1.5em; box-sizing: inherit;"><span class="gel-icon-link gel-icon-scaled" aria-describedby="Speaker-colours" style="display: inline-block; width: 24px; height: 24px; content: url(&quot;../img/link.svg&quot;); object-fit: contain; box-sizing: inherit;"></span></a></div><p style="max-width: 35rem; box-sizing: inherit; line-height: 1.54688rem; margin-top: 1.54688rem; margin-bottom: 1.54688rem; color: rgb(0, 0, 0); font-family: ReithSans, Arial, Helvetica, freesans, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 246, 246); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">A limited range of colours can be used to distinguish speakers from each other. In order of priority:</p>

Colour | RGB hex | Notes
-- | -- | --
White | #FFFFFF |  
Yellow | #FFFF00 |  
Cyan | #00FFFF |  
Green | #00FF00 | In CSS, EBU-TT and TTML this is named colour lime.

<p style="max-width: 35rem; box-sizing: inherit; line-height: 1.54688rem; margin-top: 1.54688rem; margin-bottom: 1.54688rem; color: rgb(0, 0, 0); font-family: ReithSans, Arial, Helvetica, freesans, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 246, 246); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">All of the above colours must appear on a black background to ensure maximum legibility.</p>
</body>
</html>

**Comment by CaptainTK** [comment]
Brilliant find! I did not know that.

In that case, see here: bf834afb72ce208427b5630df424cb613a68b2d3.

**Comment by CaptainTK** [comment]
Oh, and regarding black background: I don't see that as supported when feeding Kodi an SRT file.

However, it should be possible to achieve that using Kodi settings. Go to Settings->Player->Subtitles, and set "Background type" to "Box". You may be able to further optimize the settings, but the default gives me nice boxes in Kodi 20.

**Comment by sunjaxx** [comment]
Yes! This works, thanks!

PS: The bit _"All of the above colours must appear on a black background to ensure maximum legibility"_ was from the BBC guidelines, not from me: actually the main reason for me to use this KODI add-on (rather than the BBC app) is to be able: 
- *not* to have those black background boxes around the subtitles (which I personally dislike) 
- to choose a different subtitle font


:-)
